services:
  backend:
    build: ./backend
    container_name: hyrox_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://hyroxuser:hyroxpass@db/hyrox_pacer_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hyrox_net

  db:
    image: mysql:8.0
    container_name: hyrox_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hyrox_pacer_db
      MYSQL_USER: hyroxuser
      MYSQL_PASSWORD: hyroxpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hyrox_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  hyrox_net:
    driver: bridge

volumes:
  db_data:
